shopping_site/shop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name='shop'

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('product/<pk>/<slug>', views.ItemDetailView.as_view(), name='product'),
    path('add_to_cart/<pk>/<slug>',views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<pk>/<slug>',views.remove_from_cart, name='remove_from_cart'),
    path('remove_single_item_from_cart/<pk>/<slug>',views.remove_single_item_from_cart, name='remove_single_item_from_cart'),
    path('single_item_add_to_cart/<pk>/<slug>',views.single_item_add_to_cart, name='single_item_add_to_cart'),
    path('cart_summary',views.CartSummary.as_view(), name='cart_summary'),
    path('checkout/', views.Checkout.as_view(), name='checkout'),
    path('payment/<payment_option/', views.PaymentView.as_view(), name='payment'),
    path('categories/', views.categories, name='category'),
    path('s/', views.search, name='search'),
    path('add_product/', views.add_product, name='add_product'),
    path('<id>/edit_product/', views.edit_product, name='edit_product'),
    path('<id>/delete_product/', views.delete_product, name='delete_product'),
    # path('accounts/edit_profile/', views.edit_profile, name='edit_profile'),
    # to be deleted
    path('accounts/profile/', views.edit_profile, name='myprofile'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shopping_site/shopping_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('allauth.urls')),
]

shopping_site/shop/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.conf import settings
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.dispatch import receiver
from django.utils.text import slugify

CATEGORY_CHOICES = (
    ('men', 'Men'),
    ('women', 'Women')
)

SUB_CATEGORY = (
    ('shirts', 'Shirts'),
    ('dress', 'Dresses'),
    ('jeans', 'Jeans'),
    ('shoes', 'Shoes'),
    ('purse', 'Purse')
)
LABELS = (
    ('hot', 'hot'),
    ('new', 'new'),
    ('sale', 'sale')
)


class Item(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    discount_price = models.DecimalField(max_digits=10,decimal_places=2,null=True, blank=True, verbose_name='discount price')
    category = models.CharField(choices=CATEGORY_CHOICES, default=None, max_length=5)
    sub_category = models.CharField(choices=SUB_CATEGORY, default=None, max_length=6)
    label = models.CharField(choices=LABELS,default=None, null=True,
                             blank=True, max_length=4)
    description = models.CharField(max_length=2000)
    slug = models.SlugField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("shop:product", kwargs={
            'pk': self.id,
            'slug': self.slug
        })

    def get_cart_url(self):
        return reverse("shop:add_to_cart", kwargs={
            'pk': self.id,
            'slug': self.slug
        })
    
    def remove_from_cart_url(self):
        return reverse("shop:remove_from_cart", kwargs={
            'pk': self.id,
            'slug': self.slug
        })

    def remove_single_item_from_cart_url(self):
        return reverse("shop:remove_single_item_from_cart", kwargs={
            'pk': self.id,
            'slug': self.slug
        })

    def single_item_add_to_cart_url(self):
        return reverse("shop:single_item_add_to_cart", kwargs={
            'pk': self.id,
            'slug': self.slug
        })


@receiver(pre_save, sender=Item)
def pre_save_slug(sender, **kwargs):
    slug = slugify(kwargs['instance'].title)
    kwargs['instance'].slug = slug


class ItemImages(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='shop/product_images', blank=True, null=True, verbose_name="")

    def __str__(self):
        return self.item.title + ' image'

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} of {self.item.title}'

    def get_total_price(self):
        return float(self.quantity * self.item.price)
    
    def get_total_discount_price(self):
        return float(self.quantity * self.item.discount_price)

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_price()
        return self.get_total_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True, auto_now=False)
    ordered_date = models.DateTimeField()
    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        
        return total

class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    country = CountryField(multiple=False)
    address1 = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100)
    newsletter = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    zip_code = models.IntegerField()
    phone = models.IntegerField()


    def __str__(self):
        return self.user.username

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(verbose_name='Date of Birth',default='1997-01-01' ,blank=True, null=True)
    photo = models.ImageField(null=True, blank=True, default='profilepic.png', upload_to='profile_pics')


    def __str__(self):
        return self.user.username

    def delete_profile_pic(self, *args, **kwargs):
        self.photo.delete()
        super().delete(*args, **kwargs)

shopping_site/templates/add_product.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/checkout.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/checkout_responsive.css' %}">
{% endblock %}
{% block content %}
<!-- Home -->

<div class="home">
    <div class="parallax_background parallax-window" data-parallax="scroll"
        data-image-src="{% static 'images/checkout.jpg' %}" data-speed="0.8"></div>
    <div class="home_container">
        <div class="home_content">
            <div class="home_title">Add Product</div>
            <div class="breadcrumbs">
                <ul class="d-flex flex-row align-items-centFer justify-content-start">
                    <li><a href="index">Home</a></li>
                    <li><a href="cart.html">Account</a></li>
                    <li>Add Product</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- Checkout -->
<div class="checkout">
    <div class="section_container">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div
                        class="checkout_container d-flex flex-xxl-row flex-column align-items-start justify-content-start">
                        <!-- Billing -->
                        <div class="billing checkout_box">
                            <div class="checkout_title">Please Provide Product Details: </div>
                            <div class="checkout_form_container">
                                <form method="POST" id="checkout_form" enctype="multipart/form-data"
                                    class="checkout_form md-form">
                                    {% csrf_token %}
                                    {% for field in form %}
                                    {% if field.html_name == 'category' %}
                                    <div class="md-form">
                                        <div class="md-form">
                                            <select name="{{ field.html_name }}" id="{{ field.id_for_label }}" class="mdb-select md-form colorful-select dropdown-success">
                                                <option selected>Category</option>
                                                {% for name, value in form.fields.label.choices %}
                                                <option value="{{ name }}">{{ value }}</option>
                                                {% endfor %}
                                            </select>
                                    </div>
                                    {% elif field.html_name == 'sub_category' %}
                                    <div class="md-form">
                                        <div class="md-form">
                                            <select name="{{ field.html_name }}" id="{{ field.id_for_label }}" class="mdb-select md-form colorful-select dropdown-success">
                                                <option selected>Sub Category</option>
                                                {% for name, value in form.fields.label.choices %}
                                                <option class="font-weight-bold" value="{{ name }}">{{ value }}</option>
                                                {% endfor %}
                                            </select>
                                    </div>
                                    {% elif field.html_name == 'label' %}
                                    <div class="md-form">
                                        <select name="{{ field.html_name }}" id="{{ field.id_for_label }}" class="mdb-select md-form colorful-select dropdown-success">
                                            <option selected>Label (Optional)</option>
                                            {% for name, value in form.fields.label.choices %}
                                            <option value="{{ name }}">{{ value }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    {% elif field.html_name == 'discount_price' %}
                                    <div class="md-form">
                                        {{ field }}
                                        <label for="{{ field.id_for_label }}">discount price(Optional)</label>
                                    </div>
                                    {% else %}
                                    <div class="md-form">
                                        {{ field }}
                                        <label for="{{ field.id_for_label }}">{{ field.html_name }}</label>
                                    </div>
                                    {% endif %}
                                    {% endfor %}
                            </div>
                            <div>
                                <strong class="black-text font-weight-bold">Please Upload Some Images of the Product:
                                </strong>
                            </div>
                            {{ formset.management_form }}
                            {% for field in formset %}
                            <div class="md-form">
                                <div class="file-field">
                                    <div class="btn btn-rounded aqua-gradient btn-sm float-left">
                                        <span>choose file</span>
                                        {% if forloop.counter < 3 %}
                                        <input required type="file" name="form-{{ forloop.counter }}-image"
                                            accept="image/*" id="{{ field.id_forlabel }}">
                                        {% else %}
                                        <input type="file" name="form-{{ forloop.counter }}-image" accept="image/*"
                                            id="{{ field.id_forlabel }}">
                                        {% endif %}
                                    </div>
                                    <div class="file-path-wrapper">
                                        <input class="file-path validate" type="text" placeholder="Upload your file">
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>

                    <!-- Order Text -->
                    <div class="order_text">Lorem ipsum dolor sit amet, consectetur adipiscing
                        elit.
                        Proin
                        pharetra temp or so dales. Phasellus sagittis auctor gravida. Integ er
                        bibendum
                        sodales arcu id te mpus. Ut consectetur lacus.</div>

                    <button type='submit' class="checkout_button trans_200"><a>Add Product</a></button>
                </div>
            </div>
        </div>
        </form>


    </div>
</div>
{% endblock %}
{% block js %}
<script src="{% static 'js/checkout.js' %}"></script>
<script type="text/javascript" src="{%static 'js/jquery.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- MDB select -->
<script>
    // Material Select Initialization
    $(document).ready(function () {
        $('.mdb-select').materialSelect();
    });
</script>
{% endblock %}

shopping_site/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
{% endblock %}

{% block content %}
<div class="home">

	<!-- Home Slider -->
	<div class="home_slider_container">
		<div class="owl-carousel owl-theme home_slider">

			<!-- Slide -->
			<div class="owl-item animated">
				<div class="background_image" style="background-image:url(/static/images/home_slider_1.jpg)">
				</div>
				<div class="home_content_container">
					<div class="home_content">
						<div class="home_discount d-flex flex-row align-items-end justify-content-start">
							<div class="home_discount_num">30</div>
							<div class="home_discount_text">Discount on the</div>
						</div>
						<div class="home_title">New Collection</div>
						<div class="button button_1 home_button trans_200"><a href="categories">Shop
								NOW!</a></div>
					</div>
				</div>
			</div>

			<!-- Slide -->
			<div class="owl-item">
				<div class="background_image" style="background-image:url(/static/images/home_slider_1.jpg)">
				</div>
				<div class="home_content_container">
					<div class="home_content">
						<div class="home_discount d-flex flex-row align-items-end justify-content-start">
							<div class="home_discount_num">20</div>
							<div class="home_discount_text">Discount on the</div>
						</div>
						<div class="home_title">New Collection</div>
						<div class="button button_1 home_button trans_200"><a href="categories">Shop
								NOW!</a></div>
					</div>
				</div>
			</div>

			<!-- Slide -->
			<div class="owl-item">
				<div class="background_image" style="background-image:url(/static/images/home_slider_1.jpgx)">
				</div>
				<div class="home_content_container">
					<div class="home_content">
						<div class="home_discount d-flex flex-row align-items-end justify-content-start">
							<div class="home_discount_num">20</div>
							<div class="home_discount_text">Discount on the</div>
						</div>
						<div class="home_title">New Collection</div>
						<div class="button button_1 home_button trans_200"><a href="categories">Shop
								NOW!</a></div>
					</div>
				</div>
			</div>

		</div>

		<!-- Home Slider Navigation -->
		<div class="home_slider_nav home_slider_prev trans_200">
			<div class=" d-flex flex-column align-items-center justify-content-center"><img
					src="{% static 'images/prev.png' %}" alt=""></div>
		</div>
		<div class="home_slider_nav home_slider_next trans_200">
			<div class=" d-flex flex-column align-items-center justify-content-center"><img
					src="{% static 'images/next.png' %}" alt=""></div>
		</div>

	</div>
</div>

<!-- Boxes -->
{% if messages %}
{% for message in messages %}
<div class="mt-2 alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
	{{ message }}
	{{ message.tag }}
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
</div>
{% endfor %}
{% endif %}

<div class="boxes">
	<div class="section_container">
		<div class="container">
			<div class="row">

				<!-- Box -->
				<div class="col-lg-4 box_col">
					<div class="box">
						<div class="box_image"><img src="{% static 'images/box_1.jpg' %}" alt=""></div>
						<div class="box_title trans_200"><a href="categories">summer collection</a></div>
					</div>
				</div>

				<!-- Box -->
				<div class="col-lg-4 box_col">
					<div class="box">
						<div class="box_image"><img src="{% static 'images/box_2.jpg' %}" alt=""></div>
						<div class="box_title trans_200"><a href="categories">eyewear collection</a></div>
					</div>
				</div>

				<!-- Box -->
				<div class="col-lg-4 box_col">
					<div class="box">
						<div class="box_image"><img src="{% static 'images/box_3.jpg' %}" alt=""></div>
						<div class="box_title trans_200"><a href="categories">basic pieces</a></div>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>

<!-- Categories -->

<div class="categories">
	<div class="section_container">
		<div class="container">
			<div class="row">
				<div class="col text-center">
					<div class="categories_list_container">
						<ul class="categories_list d-flex flex-row align-items-center justify-content-start">
							<li><a href="categories">new arrivals</a></li>
							<li><a href="categories">recommended</a></li>
							<li><a href="categories">best sellers</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Products -->

<div class="products">
	<div class="section_container">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="products_container grid">

						<!-- Product -->
						{% for every in object_list %}
						<div class="product grid-item {{ every.get_label_display }}">
							<div class="product_inner">
								<a href="{{ every.get_absolute_url }}">
									{% for each in every.itemimages_set.all %}
									{% if forloop.counter == 1 %}
									<div class="product_image">
										<img src="{{each.image.url}}" alt="">
										<div class="product_tag">{{ every.get_label_display }}</div>
									</div>
									{% endif %}
									{% endfor %}
									<div class="product_content text-center">
										<div class="product_title"><a
												href="{{ every.get_absolute_url }}">{{ every.title }}</a></div>
										{% if every.discount_price %}
										<div class="product_price">${{ every.discount_price }}
											<span><del>${{ every.price }}</del></span>
										</div>
										{% else %}
										<div class="product_price">${{ every.price }}</div>
										{% endif %}

								</a>

							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
		<!-- PAGINATION -->
		{% if is_paginated %}
		<nav class="pagination-container">
			<div class="pagination">
				{% if page_obj.has_previous %}
				<a class="pagination-newer" href="?page={{ page_obj.previous_page_number }}">PREV</a>
				{% endif %}
				<span class="pagination-inner">
					<a href="#">1</a>
					<a class="pagination-active" href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">6</a>
				</span>
				{% if page_obj.has_next %}
				<a class="pagination-older" href="?page={{ page_obj.next_page_number }}">NEXT</a>
				{% endif %}
			</div>
		</nav>
		{% endif %}
	</div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/customized.js' %}"></script>
{% endblock %}

shopping_site/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/product.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/product_responsive.css' %}">
{% endblock %}

{% block content %}
<!-- Home -->

<div class="home">
	<div class="parallax_background parallax-window" data-parallax="scroll"
		data-image-src="{% static 'images/product_background.jpg' %}" data-speed="0.8"></div>
	<div class="home_container">
		<div class="home_content">
			<div class="home_title">Shop</div>
			<div class="breadcrumbs">
				<ul class="d-flex flex-row align-items-center justify-content-start">
					<li><a href="index.html">Home</a></li>
					<li><a href="categories.html">{{ object.get_category_display }}</a></li>
					<li><a href="categories.html">{{ object.get_sub_category_display }}</a></li>
					<li>{{ object.title }}</li>
				</ul>
			</div>
		</div>
	</div>
</div>

<!-- Products -->

<div class="product">

	<!-- Sorting & Filtering -->
	<div class="products_bar">
		<div class="section_container">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="products_bar_content d-flex flex-row align-items-center justify-content-start">
							<div class="product_categories">
								<ul class="d-flex flex-row align-items-start justify-content-start flex-wrap">
									<li class="active"><a href="#">All</a></li>
									<li><a href="#">Hot Products</a></li>
									<li><a href="#">New Products</a></li>
									<li><a href="#">Sale Products</a></li>
									{% if object.user == request.user %}
									<li id="navbar-static-tools" class="dropdown">
										<a class="black-text dropdown-toggle" data-toggle="dropdown"
											aria-haspopup="true" aria-expanded="false">
											Tools</a>
										<div class="dropdown-menu dropdown-menu-right dropdown-info"
											aria-labelledby="navbar-tools">
											<a class="dropdown-item d-xl-none" href="#">Sale Products</a>
											<a class="dropdown-item" href="{% url 'shop:edit_product' id=object.id %}">Edit this product</a>
											<a class="dropdown-item" href="{% url 'shop:delete_product' id=object.id %}">Delete this product</a>
										</div>
									</li>
									{% endif %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Product Content -->
	<div class="section_container">
		<div class="container">
			<div class="row">
				<div class="col">

					<div
						class="product_content_container d-flex flex-lg-row flex-column align-items-start justify-content-start">
						<div class="product_content order-lg-1 order-2">
							<div class="product_content_inner">
								{% for each in object.itemimages_set.all %}
								{% if forloop.counter == 1 %}
								<div
									class="product_image_row d-flex flex-md-row flex-column align-items-md-end align-items-start justify-content-start">
									<div class="product_image_{{ forloop.counter }} product_image">
										<img src="{{ each.image.url }}" alt="{{ object.title }}">
									</div>
									{% elif forloop.counter == 2 %}
									<div class="product_image_{{ forloop.counter }} product_image"><img
											src="{{ each.image.url }}" alt="{{ object.title }}"></div>
								</div>
								{% elif forloop.counter == 3 %}
								<div class="product_image_row">
									<div class="product_image_{{forloop.counter}} product_image"><img
											src="{{ each.image.url }}" alt="{{ object.title }}"></div>
								</div>
								{% elif forloop.counter == 4 %}
								<div
									class="product_image_row d-flex flex-md-row flex-column align-items-start justify-content-start">
									<div class="product_image_{{ forloop.counter }} product_image"><img
											src="{{ each.image.url }}" alt="{{ object.title }}"></div>
									{% elif forloop.counter == 5 %}
									<div class="product_image_{{ forloop.counter }} product_image"><img
											src="{{ each.image.url }}" alt="{{ object.title }}"></div>
								</div>
								{% endif %}
								{% endfor %}
								<div>
									<h1 class="p-2">product description:</h1>
									<h3 style="color: #414b56;" class="mx-4 px-2 py-2">
										{{ object.description }}
									</h3>
								</div>
							</div>
						</div>
						<div class="product_sidebar order-lg-2 order-1">
							<form action="#" id="product_form" class="product_form">
								<div class="product_name">{{ object.title }}</div>
								{% if object.discount_price %}
								<div class="product_price">${{ object.discount_price }}
									<span><del
											style="font-size: medium; opacity: 0.50; ">${{ object.price }}</del></span>
								</div>
								{% else %}
								<div class="product_price">${{ object.price }}</div>
								{% endif %}
								<div class="product_color">Color: <span>Brown</span></div>
								<div class="product_size">
									<div class="product_size_title">Select Size</div>
									<div class="product_size_list">
										<ul>
											<li class="size_available">
												<input type="radio" id="radio_1" name="product_radio"
													class="regular_radio radio_1">
												<label for="radio_1">35</label>
											</li>
											<li class="size_available">
												<input type="radio" id="radio_2" name="product_radio"
													class="regular_radio radio_2">
												<label for="radio_2">36</label>
											</li>
											<li class="size_available">
												<input type="radio" id="radio_3" name="product_radio"
													class="regular_radio radio_3">
												<label for="radio_3">37</label>
											</li>
											<li class="size_available">
												<input type="radio" id="radio_4" name="product_radio"
													class="regular_radio radio_4">
												<label for="radio_4">38</label>
											</li>
											<li>
												<input type="radio" id="radio_5" name="product_radio"
													class="regular_radio radio_5" disabled>
												<label for="radio_5">39</label>
											</li>
											<li>
												<input type="radio" id="radio_6" name="product_radio"
													class="regular_radio radio_6" disabled>
												<label for="radio_6">40</label>
											</li>
										</ul>
									</div>
								</div>
								{% if messages %}
								{% for message in messages %}
								<div class="mt-2 alert alert-{{ message.tags }} alert-dismissible fade show"
									role="alert">
									{{ message }}
									{{ message.tag }}
									<button type="button" class="close" data-dismiss="alert" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								{% endfor %}
								{% endif %}
								<button class="cart_button trans_200"><a href="{{ object.get_cart_url }}">add to
										cart</a></button>
								<button class="delete_cart_button trans_200"><a
										href="{{ object.remove_from_cart_url }}">remove from cart</a></button>
								<div class="similar_products_button trans_200"><a href="/categories">see similar
										products</a></div>
							</form>
							<div class="product_links">
								<ul class="text-center">
									<li><a href="#">See guide</a></li>
									<li><a href="#">Shipping</a></li>
									<li><a href="#">Returns</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'js/product.js' %}"></script>
{% endblock %}

shopping_site/templates/results.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
{% endblock %}

{% block content %}


<h1>you searched for: {{ query }}</h1>
<!-- Products -->
{% if empty %}
<h1>No Results For : {{ query }}</h1>
{% else %}
<div class="products">
	<div class="section_container">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="products_container grid">

						<!-- Product -->
						{% for every in products %}
						<div class="product grid-item hot">
							<div class="product_inner">
								{% for each in every.productimage_set.all %}
								<a href="/product/{{ every.id }}">
									<div class="product_image">
										<img src="/media/{{each.image}}" alt="">
										<!-- <div class="product_tag">hot</div> -->
									</div>
									<div class="product_content text-center">
										<div class="product_title"><a href="product">{{ every.product_name }}</a></div>
										<div class="product_price">${{ every.price }}</div>
								</a>
								{% endfor %}
								<button id='p_id{{i.id}}'
									class="product_button ml-auto mr-auto trans_200 cartisjs"><a>Add to
										cart</a></button>

							</div>
						</div>
					</div>
					{% endfor %}
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'js/custom.js' %}"></script>
{% endblock %}